name: OneSeventeen Photography
favicon: null
layout_spectrum: 0.9477922709193081
typography_spectrum: 0.5745578755158931
title: OneSeventeen Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.31880524032749236
  lightness: 0.7496063928119838
  saturation: 0.880392471794039
  rhythmicContrast: 0.7829724235925823
purpose: []
